Repository jedster1111/bananagram-mk2, pull requests merged in 2019-07, with the labels that each got.

#32 GH-31 Added styled-component to recommended extensions and updated docs
  .vscode/extensions.json
  bananagram-frontend/README.md
Labels: DX

#35 GH-34 Fixed header and footer height and stretched col width
  bananagram-frontend/src/App.tsx
  bananagram-frontend/src/components/Pages/GridPage.tsx
Labels: grid

#37 GH-36 Added import order linting rules
  bananagram-frontend/.eslintrc.json
  bananagram-frontend/package.json
  bananagram-frontend/src/App.test.tsx
  bananagram-frontend/src/App.tsx
  bananagram-frontend/src/components/Grid/Grid.test.tsx
  bananagram-frontend/src/components/Grid/Grid.tsx
  bananagram-frontend/src/components/Grid/GridControls/GridControls.tsx
  bananagram-frontend/src/components/Grid/GridControls/OffsetControlButton.test.tsx
  bananagram-frontend/src/components/Grid/GridControls/OffsetControlButton.tsx
  bananagram-frontend/src/components/Grid/GridInfo/GridInfo.test.tsx
  bananagram-frontend/src/components/Grid/GridRow.tsx
  bananagram-frontend/src/components/Grid/GridSquare.test.tsx
  bananagram-frontend/src/components/Grid/GridSquare.tsx
  bananagram-frontend/src/components/Grid/createSquares.test.ts
  bananagram-frontend/src/components/Grid/createSquares.ts
  bananagram-frontend/src/components/Pages/GridPage.test.tsx
  bananagram-frontend/src/components/Pages/GridPage.tsx
  bananagram-frontend/src/hooks/useWhyDidYouUpdate.test.ts
  bananagram-frontend/src/hooks/useWhyDidYouUpdate.ts
  bananagram-frontend/src/index.tsx
  yarn.lock
Labels: DX

#41 GH-40 added trailing commas to prettier
  bananagram-frontend/.eslintrc.json
  bananagram-frontend/src/App.tsx
  bananagram-frontend/src/components/Grid/Grid.test.tsx
  bananagram-frontend/src/components/Grid/Grid.tsx
  bananagram-frontend/src/components/Grid/GridControls/GridControls.tsx
  bananagram-frontend/src/components/Grid/GridControls/OffsetControlButton.test.tsx
  bananagram-frontend/src/components/Grid/GridControls/OffsetControlButton.tsx
  bananagram-frontend/src/components/Grid/GridInfo/GridInfo.test.tsx
  bananagram-frontend/src/components/Grid/GridRow.tsx
  bananagram-frontend/src/components/Grid/GridSquare.test.tsx
  bananagram-frontend/src/components/Grid/createSquares.test.ts
  bananagram-frontend/src/components/Grid/createSquares.ts
  bananagram-frontend/src/hooks/useWhyDidYouUpdate.test.ts
  bananagram-frontend/src/hooks/useWhyDidYouUpdate.ts
Labels: DX

#42 GH-9 Created files and docs for setting up CI server
  .gitignore
  .vscode/settings.json
  Jenkinsfile
  ci-server/README.md
  ci-server/ansible/README.md
  ci-server/ansible/create_user.yaml
  ci-server/ansible/start_jenkins.yaml
  ci-server/ci-server-files/docker-compose/.env
  ci-server/ci-server-files/docker-compose/docker-compose.yaml
  ci-server/ci-server-files/dockerfiles/jenkins/Dockerfile
  ci-server/ci-server-files/dockerfiles/jenkins/jenkins-plugins
  ci-server/ci-server-files/dockerfiles/jenkins/jenkins.yaml
  ci-server/ci-server-files/jenkins/default-user.groovy
  ci-server/terraform/README.terraform.md
  ci-server/terraform/main.tf
  ci-server/terraform/variables.tf
Labels: CI, DX, docker, documentation, jenkins, testing

#45 Gh 11
  bananagram-frontend/src/components/Grid/Grid.tsx
  bananagram-frontend/src/components/Grid/GridControls/GridControls.test.tsx
  bananagram-frontend/src/components/Grid/GridControls/GridControls.tsx
  bananagram-frontend/src/components/Pages/GridPage.test.tsx
  bananagram-frontend/src/components/Pages/GridPage.tsx
Labels: grid, offset, zoom

#55 GH-54 Moved banangram-frontend inside of packages/ folder
  Jenkinsfile
  package.json
  packages/bananagram-frontend/.dockerignore
  packages/bananagram-frontend/.eslintrc.json
  packages/bananagram-frontend/.gitignore
  packages/bananagram-frontend/Dockerfile
  packages/bananagram-frontend/README.md
  packages/bananagram-frontend/package.json
  packages/bananagram-frontend/public/favicon.ico
  packages/bananagram-frontend/public/index.html
  packages/bananagram-frontend/public/manifest.json
  packages/bananagram-frontend/src/App.test.tsx
  packages/bananagram-frontend/src/App.tsx
  packages/bananagram-frontend/src/components/Grid/Grid.test.tsx
  packages/bananagram-frontend/src/components/Grid/Grid.tsx
  packages/bananagram-frontend/src/components/Grid/GridControls/GridControls.test.tsx
  packages/bananagram-frontend/src/components/Grid/GridControls/GridControls.tsx
  packages/bananagram-frontend/src/components/Grid/GridControls/OffsetControlButton.test.tsx
  packages/bananagram-frontend/src/components/Grid/GridControls/OffsetControlButton.tsx
  packages/bananagram-frontend/src/components/Grid/GridInfo/GridInfo.test.tsx
  packages/bananagram-frontend/src/components/Grid/GridInfo/GridInfo.tsx
  packages/bananagram-frontend/src/components/Grid/GridRow.tsx
  packages/bananagram-frontend/src/components/Grid/GridSquare.test.tsx
  packages/bananagram-frontend/src/components/Grid/GridSquare.tsx
  packages/bananagram-frontend/src/components/Grid/createSquares.test.ts
  packages/bananagram-frontend/src/components/Grid/createSquares.ts
  packages/bananagram-frontend/src/components/Grid/gridTypes.ts
  packages/bananagram-frontend/src/components/Pages/GridPage.test.tsx
  packages/bananagram-frontend/src/components/Pages/GridPage.tsx
  packages/bananagram-frontend/src/components/common/Button.tsx
  packages/bananagram-frontend/src/hooks/useWhyDidYouUpdate.test.ts
  packages/bananagram-frontend/src/hooks/useWhyDidYouUpdate.ts
  packages/bananagram-frontend/src/index.css
  packages/bananagram-frontend/src/index.tsx
  packages/bananagram-frontend/src/react-app-env.d.ts
  packages/bananagram-frontend/src/setupTests.ts
  packages/bananagram-frontend/src/types.ts
  packages/bananagram-frontend/src/utils/shallowEquals.test.ts
  packages/bananagram-frontend/src/utils/shallowEquals.ts
  packages/bananagram-frontend/src/utils/test/getSquareIndex.tsx
  packages/bananagram-frontend/tsconfig.json
  packages/bananagram-frontend/yarn.lock
Labels: DX
